### ISSUE TITLE
what is the required version of : I2C_device_Arduino 

### ISSUE THREAD

**Issue by micclfr** [loco-engineering/simpledcc-arduino#3]
There is not the required version for this .lib

I2C_device_Arduino (remove 2 tests file after you install it - Arduino/libraries/I2C_device_Arduino/src/test_LM75B.h and .cpp with the same name otherwise you'll get errors during building)

I keep getting error 👍 

In file included from C:\Users\claud\Documents\Arduino\libraries\I2C_device_Arduino\src\I2C_device.h:16,
                 from C:\Users\claud\Documents\Arduino\libraries\I2C_device_Arduino\src\I2C_device.cpp:1:
C:\Users\claud\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.17\libraries\Wire\src/Wire.h: In member function 'int I2C_device::rx(uint8_t*, uint16_t)':
C:\Users\claud\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.17\libraries\Wire\src/Wire.h:127:13: note: candidate 1: 'uint8_t TwoWire::requestFrom(int, int)'
     uint8_t requestFrom(int address, int size);
             ^~~~~~~~~~~
C:\Users\claud\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.17\libraries\Wire\src/Wire.h:125:13: note: candidate 2: 'uint8_t TwoWire::requestFrom(uint8_t, uint8_t)'
     uint8_t requestFrom(uint8_t address, uint8_t size);
             ^~~~~~~~~~~

**Comment by hej-turbodev** [comment]
It's not an error; it's just a warning that we'll address. The firmware should still be built, and you can upload it. We use I2C_device_Arduino 1.1.0 for the production firmware. Added the version to Readme.
